FROM python:3.5

RUN pip3 install tarantool

# ENV STEEM_USER   steem
# ENV STEEM_HOME   /home/steem

ENV STEEM_HOME   /steem


# RUN useradd -m $STEEM_USER && chown -R $STEEM_USER $STEEM_HOME

# USER $STEEM_USER
WORKDIR $STEEM_HOME

COPY datafeed.py .
COPY python-steem python-steem

RUN cd ./python-steem && python3 setup.py install

CMD ["python", "./datafeed.py"]
