version: '2'

services:

  datastore:
    image: goloschain/golosnotify/datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    ports:
      - "3301:3301"
      - "8082:8082"
    volumes:
      - ./data:/var/lib/tarantool
      - ./:/home/src
