version: '3'

services:

  datafeed:
    image: goloschain/golosnotify/datafeed
    build:
      context: .
      dockerfile: Dockerfile-datafeed
    links:
      - datastore
    environment:
      - STEEMIT_WEBSOCKET_CONNECTION=wss://rpc.sandbox.golos.io
      - STEEMIT_WEBCLIENT_ADDRESS=https://sandbox.golos.io
      - STEEMIT_IMAGE_PROXY_PREFIX=https://imgp.golos.io/
      - STEEMIT_TITLE='Golos'

  datastore:
    image: goloschain/golosnotify/datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    ports:
      - "3301:3301"
    volumes:
      # - ./data:/var/lib/tarantool
      # - ./:/home/src
      - data:/var/lib/tarantool/
      - log:/var/log/tarantool/

volumes:

    data:
    log:

